# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aso/Galet-Med_work/v11/Galet-Med-v11

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aso/Galet-Med_work/v11/Galet-Med-v11

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aso/Galet-Med_work/v11/Galet-Med-v11/CMakeFiles /Users/aso/Galet-Med_work/v11/Galet-Med-v11//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aso/Galet-Med_work/v11/Galet-Med-v11/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Galet

# Build rule for target.
Galet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Galet
.PHONY : Galet

# fast build rule for target.
Galet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/build
.PHONY : Galet/fast

Galet.o: Galet.cc.o
.PHONY : Galet.o

# target to build an object file
Galet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/Galet.cc.o
.PHONY : Galet.cc.o

Galet.i: Galet.cc.i
.PHONY : Galet.i

# target to preprocess a source file
Galet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/Galet.cc.i
.PHONY : Galet.cc.i

Galet.s: Galet.cc.s
.PHONY : Galet.s

# target to generate assembly for a file
Galet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/Galet.cc.s
.PHONY : Galet.cc.s

src/G4MMaterialFileConstruction.o: src/G4MMaterialFileConstruction.cc.o
.PHONY : src/G4MMaterialFileConstruction.o

# target to build an object file
src/G4MMaterialFileConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MMaterialFileConstruction.cc.o
.PHONY : src/G4MMaterialFileConstruction.cc.o

src/G4MMaterialFileConstruction.i: src/G4MMaterialFileConstruction.cc.i
.PHONY : src/G4MMaterialFileConstruction.i

# target to preprocess a source file
src/G4MMaterialFileConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MMaterialFileConstruction.cc.i
.PHONY : src/G4MMaterialFileConstruction.cc.i

src/G4MMaterialFileConstruction.s: src/G4MMaterialFileConstruction.cc.s
.PHONY : src/G4MMaterialFileConstruction.s

# target to generate assembly for a file
src/G4MMaterialFileConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MMaterialFileConstruction.cc.s
.PHONY : src/G4MMaterialFileConstruction.cc.s

src/G4MMaterialFileMessenger.o: src/G4MMaterialFileMessenger.cc.o
.PHONY : src/G4MMaterialFileMessenger.o

# target to build an object file
src/G4MMaterialFileMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MMaterialFileMessenger.cc.o
.PHONY : src/G4MMaterialFileMessenger.cc.o

src/G4MMaterialFileMessenger.i: src/G4MMaterialFileMessenger.cc.i
.PHONY : src/G4MMaterialFileMessenger.i

# target to preprocess a source file
src/G4MMaterialFileMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MMaterialFileMessenger.cc.i
.PHONY : src/G4MMaterialFileMessenger.cc.i

src/G4MMaterialFileMessenger.s: src/G4MMaterialFileMessenger.cc.s
.PHONY : src/G4MMaterialFileMessenger.s

# target to generate assembly for a file
src/G4MMaterialFileMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MMaterialFileMessenger.cc.s
.PHONY : src/G4MMaterialFileMessenger.cc.s

src/G4MTritium.o: src/G4MTritium.cc.o
.PHONY : src/G4MTritium.o

# target to build an object file
src/G4MTritium.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MTritium.cc.o
.PHONY : src/G4MTritium.cc.o

src/G4MTritium.i: src/G4MTritium.cc.i
.PHONY : src/G4MTritium.i

# target to preprocess a source file
src/G4MTritium.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MTritium.cc.i
.PHONY : src/G4MTritium.cc.i

src/G4MTritium.s: src/G4MTritium.cc.s
.PHONY : src/G4MTritium.s

# target to generate assembly for a file
src/G4MTritium.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/G4MTritium.cc.s
.PHONY : src/G4MTritium.cc.s

src/GaletActionInitialization.o: src/GaletActionInitialization.cc.o
.PHONY : src/GaletActionInitialization.o

# target to build an object file
src/GaletActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletActionInitialization.cc.o
.PHONY : src/GaletActionInitialization.cc.o

src/GaletActionInitialization.i: src/GaletActionInitialization.cc.i
.PHONY : src/GaletActionInitialization.i

# target to preprocess a source file
src/GaletActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletActionInitialization.cc.i
.PHONY : src/GaletActionInitialization.cc.i

src/GaletActionInitialization.s: src/GaletActionInitialization.cc.s
.PHONY : src/GaletActionInitialization.s

# target to generate assembly for a file
src/GaletActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletActionInitialization.cc.s
.PHONY : src/GaletActionInitialization.cc.s

src/GaletDetectorConstruction.o: src/GaletDetectorConstruction.cc.o
.PHONY : src/GaletDetectorConstruction.o

# target to build an object file
src/GaletDetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletDetectorConstruction.cc.o
.PHONY : src/GaletDetectorConstruction.cc.o

src/GaletDetectorConstruction.i: src/GaletDetectorConstruction.cc.i
.PHONY : src/GaletDetectorConstruction.i

# target to preprocess a source file
src/GaletDetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletDetectorConstruction.cc.i
.PHONY : src/GaletDetectorConstruction.cc.i

src/GaletDetectorConstruction.s: src/GaletDetectorConstruction.cc.s
.PHONY : src/GaletDetectorConstruction.s

# target to generate assembly for a file
src/GaletDetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletDetectorConstruction.cc.s
.PHONY : src/GaletDetectorConstruction.cc.s

src/GaletDetectorConstructionMessenger.o: src/GaletDetectorConstructionMessenger.cc.o
.PHONY : src/GaletDetectorConstructionMessenger.o

# target to build an object file
src/GaletDetectorConstructionMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletDetectorConstructionMessenger.cc.o
.PHONY : src/GaletDetectorConstructionMessenger.cc.o

src/GaletDetectorConstructionMessenger.i: src/GaletDetectorConstructionMessenger.cc.i
.PHONY : src/GaletDetectorConstructionMessenger.i

# target to preprocess a source file
src/GaletDetectorConstructionMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletDetectorConstructionMessenger.cc.i
.PHONY : src/GaletDetectorConstructionMessenger.cc.i

src/GaletDetectorConstructionMessenger.s: src/GaletDetectorConstructionMessenger.cc.s
.PHONY : src/GaletDetectorConstructionMessenger.s

# target to generate assembly for a file
src/GaletDetectorConstructionMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletDetectorConstructionMessenger.cc.s
.PHONY : src/GaletDetectorConstructionMessenger.cc.s

src/GaletEventAction.o: src/GaletEventAction.cc.o
.PHONY : src/GaletEventAction.o

# target to build an object file
src/GaletEventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletEventAction.cc.o
.PHONY : src/GaletEventAction.cc.o

src/GaletEventAction.i: src/GaletEventAction.cc.i
.PHONY : src/GaletEventAction.i

# target to preprocess a source file
src/GaletEventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletEventAction.cc.i
.PHONY : src/GaletEventAction.cc.i

src/GaletEventAction.s: src/GaletEventAction.cc.s
.PHONY : src/GaletEventAction.s

# target to generate assembly for a file
src/GaletEventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletEventAction.cc.s
.PHONY : src/GaletEventAction.cc.s

src/GaletEventActionMessenger.o: src/GaletEventActionMessenger.cc.o
.PHONY : src/GaletEventActionMessenger.o

# target to build an object file
src/GaletEventActionMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletEventActionMessenger.cc.o
.PHONY : src/GaletEventActionMessenger.cc.o

src/GaletEventActionMessenger.i: src/GaletEventActionMessenger.cc.i
.PHONY : src/GaletEventActionMessenger.i

# target to preprocess a source file
src/GaletEventActionMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletEventActionMessenger.cc.i
.PHONY : src/GaletEventActionMessenger.cc.i

src/GaletEventActionMessenger.s: src/GaletEventActionMessenger.cc.s
.PHONY : src/GaletEventActionMessenger.s

# target to generate assembly for a file
src/GaletEventActionMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletEventActionMessenger.cc.s
.PHONY : src/GaletEventActionMessenger.cc.s

src/GaletHit.o: src/GaletHit.cc.o
.PHONY : src/GaletHit.o

# target to build an object file
src/GaletHit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletHit.cc.o
.PHONY : src/GaletHit.cc.o

src/GaletHit.i: src/GaletHit.cc.i
.PHONY : src/GaletHit.i

# target to preprocess a source file
src/GaletHit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletHit.cc.i
.PHONY : src/GaletHit.cc.i

src/GaletHit.s: src/GaletHit.cc.s
.PHONY : src/GaletHit.s

# target to generate assembly for a file
src/GaletHit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletHit.cc.s
.PHONY : src/GaletHit.cc.s

src/GaletMagneticField.o: src/GaletMagneticField.cc.o
.PHONY : src/GaletMagneticField.o

# target to build an object file
src/GaletMagneticField.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletMagneticField.cc.o
.PHONY : src/GaletMagneticField.cc.o

src/GaletMagneticField.i: src/GaletMagneticField.cc.i
.PHONY : src/GaletMagneticField.i

# target to preprocess a source file
src/GaletMagneticField.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletMagneticField.cc.i
.PHONY : src/GaletMagneticField.cc.i

src/GaletMagneticField.s: src/GaletMagneticField.cc.s
.PHONY : src/GaletMagneticField.s

# target to generate assembly for a file
src/GaletMagneticField.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletMagneticField.cc.s
.PHONY : src/GaletMagneticField.cc.s

src/GaletNestedPhantomParameterisation.o: src/GaletNestedPhantomParameterisation.cc.o
.PHONY : src/GaletNestedPhantomParameterisation.o

# target to build an object file
src/GaletNestedPhantomParameterisation.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletNestedPhantomParameterisation.cc.o
.PHONY : src/GaletNestedPhantomParameterisation.cc.o

src/GaletNestedPhantomParameterisation.i: src/GaletNestedPhantomParameterisation.cc.i
.PHONY : src/GaletNestedPhantomParameterisation.i

# target to preprocess a source file
src/GaletNestedPhantomParameterisation.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletNestedPhantomParameterisation.cc.i
.PHONY : src/GaletNestedPhantomParameterisation.cc.i

src/GaletNestedPhantomParameterisation.s: src/GaletNestedPhantomParameterisation.cc.s
.PHONY : src/GaletNestedPhantomParameterisation.s

# target to generate assembly for a file
src/GaletNestedPhantomParameterisation.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletNestedPhantomParameterisation.cc.s
.PHONY : src/GaletNestedPhantomParameterisation.cc.s

src/GaletPhantom.o: src/GaletPhantom.cc.o
.PHONY : src/GaletPhantom.o

# target to build an object file
src/GaletPhantom.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletPhantom.cc.o
.PHONY : src/GaletPhantom.cc.o

src/GaletPhantom.i: src/GaletPhantom.cc.i
.PHONY : src/GaletPhantom.i

# target to preprocess a source file
src/GaletPhantom.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletPhantom.cc.i
.PHONY : src/GaletPhantom.cc.i

src/GaletPhantom.s: src/GaletPhantom.cc.s
.PHONY : src/GaletPhantom.s

# target to generate assembly for a file
src/GaletPhantom.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletPhantom.cc.s
.PHONY : src/GaletPhantom.cc.s

src/GaletPrimaryGeneratorAction.o: src/GaletPrimaryGeneratorAction.cc.o
.PHONY : src/GaletPrimaryGeneratorAction.o

# target to build an object file
src/GaletPrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletPrimaryGeneratorAction.cc.o
.PHONY : src/GaletPrimaryGeneratorAction.cc.o

src/GaletPrimaryGeneratorAction.i: src/GaletPrimaryGeneratorAction.cc.i
.PHONY : src/GaletPrimaryGeneratorAction.i

# target to preprocess a source file
src/GaletPrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletPrimaryGeneratorAction.cc.i
.PHONY : src/GaletPrimaryGeneratorAction.cc.i

src/GaletPrimaryGeneratorAction.s: src/GaletPrimaryGeneratorAction.cc.s
.PHONY : src/GaletPrimaryGeneratorAction.s

# target to generate assembly for a file
src/GaletPrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletPrimaryGeneratorAction.cc.s
.PHONY : src/GaletPrimaryGeneratorAction.cc.s

src/GaletRunAction.o: src/GaletRunAction.cc.o
.PHONY : src/GaletRunAction.o

# target to build an object file
src/GaletRunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletRunAction.cc.o
.PHONY : src/GaletRunAction.cc.o

src/GaletRunAction.i: src/GaletRunAction.cc.i
.PHONY : src/GaletRunAction.i

# target to preprocess a source file
src/GaletRunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletRunAction.cc.i
.PHONY : src/GaletRunAction.cc.i

src/GaletRunAction.s: src/GaletRunAction.cc.s
.PHONY : src/GaletRunAction.s

# target to generate assembly for a file
src/GaletRunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletRunAction.cc.s
.PHONY : src/GaletRunAction.cc.s

src/GaletRunActionMessenger.o: src/GaletRunActionMessenger.cc.o
.PHONY : src/GaletRunActionMessenger.o

# target to build an object file
src/GaletRunActionMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletRunActionMessenger.cc.o
.PHONY : src/GaletRunActionMessenger.cc.o

src/GaletRunActionMessenger.i: src/GaletRunActionMessenger.cc.i
.PHONY : src/GaletRunActionMessenger.i

# target to preprocess a source file
src/GaletRunActionMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletRunActionMessenger.cc.i
.PHONY : src/GaletRunActionMessenger.cc.i

src/GaletRunActionMessenger.s: src/GaletRunActionMessenger.cc.s
.PHONY : src/GaletRunActionMessenger.s

# target to generate assembly for a file
src/GaletRunActionMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletRunActionMessenger.cc.s
.PHONY : src/GaletRunActionMessenger.cc.s

src/GaletSD.o: src/GaletSD.cc.o
.PHONY : src/GaletSD.o

# target to build an object file
src/GaletSD.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletSD.cc.o
.PHONY : src/GaletSD.cc.o

src/GaletSD.i: src/GaletSD.cc.i
.PHONY : src/GaletSD.i

# target to preprocess a source file
src/GaletSD.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletSD.cc.i
.PHONY : src/GaletSD.cc.i

src/GaletSD.s: src/GaletSD.cc.s
.PHONY : src/GaletSD.s

# target to generate assembly for a file
src/GaletSD.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletSD.cc.s
.PHONY : src/GaletSD.cc.s

src/GaletSteppingAction.o: src/GaletSteppingAction.cc.o
.PHONY : src/GaletSteppingAction.o

# target to build an object file
src/GaletSteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletSteppingAction.cc.o
.PHONY : src/GaletSteppingAction.cc.o

src/GaletSteppingAction.i: src/GaletSteppingAction.cc.i
.PHONY : src/GaletSteppingAction.i

# target to preprocess a source file
src/GaletSteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletSteppingAction.cc.i
.PHONY : src/GaletSteppingAction.cc.i

src/GaletSteppingAction.s: src/GaletSteppingAction.cc.s
.PHONY : src/GaletSteppingAction.s

# target to generate assembly for a file
src/GaletSteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletSteppingAction.cc.s
.PHONY : src/GaletSteppingAction.cc.s

src/GaletTrackInformation.o: src/GaletTrackInformation.cc.o
.PHONY : src/GaletTrackInformation.o

# target to build an object file
src/GaletTrackInformation.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTrackInformation.cc.o
.PHONY : src/GaletTrackInformation.cc.o

src/GaletTrackInformation.i: src/GaletTrackInformation.cc.i
.PHONY : src/GaletTrackInformation.i

# target to preprocess a source file
src/GaletTrackInformation.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTrackInformation.cc.i
.PHONY : src/GaletTrackInformation.cc.i

src/GaletTrackInformation.s: src/GaletTrackInformation.cc.s
.PHONY : src/GaletTrackInformation.s

# target to generate assembly for a file
src/GaletTrackInformation.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTrackInformation.cc.s
.PHONY : src/GaletTrackInformation.cc.s

src/GaletTrackingAction.o: src/GaletTrackingAction.cc.o
.PHONY : src/GaletTrackingAction.o

# target to build an object file
src/GaletTrackingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTrackingAction.cc.o
.PHONY : src/GaletTrackingAction.cc.o

src/GaletTrackingAction.i: src/GaletTrackingAction.cc.i
.PHONY : src/GaletTrackingAction.i

# target to preprocess a source file
src/GaletTrackingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTrackingAction.cc.i
.PHONY : src/GaletTrackingAction.cc.i

src/GaletTrackingAction.s: src/GaletTrackingAction.cc.s
.PHONY : src/GaletTrackingAction.s

# target to generate assembly for a file
src/GaletTrackingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTrackingAction.cc.s
.PHONY : src/GaletTrackingAction.cc.s

src/GaletTriggerSD.o: src/GaletTriggerSD.cc.o
.PHONY : src/GaletTriggerSD.o

# target to build an object file
src/GaletTriggerSD.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTriggerSD.cc.o
.PHONY : src/GaletTriggerSD.cc.o

src/GaletTriggerSD.i: src/GaletTriggerSD.cc.i
.PHONY : src/GaletTriggerSD.i

# target to preprocess a source file
src/GaletTriggerSD.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTriggerSD.cc.i
.PHONY : src/GaletTriggerSD.cc.i

src/GaletTriggerSD.s: src/GaletTriggerSD.cc.s
.PHONY : src/GaletTriggerSD.s

# target to generate assembly for a file
src/GaletTriggerSD.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/GaletTriggerSD.cc.s
.PHONY : src/GaletTriggerSD.cc.s

src/MACParticleConstruction.o: src/MACParticleConstruction.cc.o
.PHONY : src/MACParticleConstruction.o

# target to build an object file
src/MACParticleConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACParticleConstruction.cc.o
.PHONY : src/MACParticleConstruction.cc.o

src/MACParticleConstruction.i: src/MACParticleConstruction.cc.i
.PHONY : src/MACParticleConstruction.i

# target to preprocess a source file
src/MACParticleConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACParticleConstruction.cc.i
.PHONY : src/MACParticleConstruction.cc.i

src/MACParticleConstruction.s: src/MACParticleConstruction.cc.s
.PHONY : src/MACParticleConstruction.s

# target to generate assembly for a file
src/MACParticleConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACParticleConstruction.cc.s
.PHONY : src/MACParticleConstruction.cc.s

src/MACPhysicsList.o: src/MACPhysicsList.cc.o
.PHONY : src/MACPhysicsList.o

# target to build an object file
src/MACPhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACPhysicsList.cc.o
.PHONY : src/MACPhysicsList.cc.o

src/MACPhysicsList.i: src/MACPhysicsList.cc.i
.PHONY : src/MACPhysicsList.i

# target to preprocess a source file
src/MACPhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACPhysicsList.cc.i
.PHONY : src/MACPhysicsList.cc.i

src/MACPhysicsList.s: src/MACPhysicsList.cc.s
.PHONY : src/MACPhysicsList.s

# target to generate assembly for a file
src/MACPhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACPhysicsList.cc.s
.PHONY : src/MACPhysicsList.cc.s

src/MACPhysicsListMessenger.o: src/MACPhysicsListMessenger.cc.o
.PHONY : src/MACPhysicsListMessenger.o

# target to build an object file
src/MACPhysicsListMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACPhysicsListMessenger.cc.o
.PHONY : src/MACPhysicsListMessenger.cc.o

src/MACPhysicsListMessenger.i: src/MACPhysicsListMessenger.cc.i
.PHONY : src/MACPhysicsListMessenger.i

# target to preprocess a source file
src/MACPhysicsListMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACPhysicsListMessenger.cc.i
.PHONY : src/MACPhysicsListMessenger.cc.i

src/MACPhysicsListMessenger.s: src/MACPhysicsListMessenger.cc.s
.PHONY : src/MACPhysicsListMessenger.s

# target to generate assembly for a file
src/MACPhysicsListMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Galet.dir/build.make CMakeFiles/Galet.dir/src/MACPhysicsListMessenger.cc.s
.PHONY : src/MACPhysicsListMessenger.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Galet"
	@echo "... Galet.o"
	@echo "... Galet.i"
	@echo "... Galet.s"
	@echo "... src/G4MMaterialFileConstruction.o"
	@echo "... src/G4MMaterialFileConstruction.i"
	@echo "... src/G4MMaterialFileConstruction.s"
	@echo "... src/G4MMaterialFileMessenger.o"
	@echo "... src/G4MMaterialFileMessenger.i"
	@echo "... src/G4MMaterialFileMessenger.s"
	@echo "... src/G4MTritium.o"
	@echo "... src/G4MTritium.i"
	@echo "... src/G4MTritium.s"
	@echo "... src/GaletActionInitialization.o"
	@echo "... src/GaletActionInitialization.i"
	@echo "... src/GaletActionInitialization.s"
	@echo "... src/GaletDetectorConstruction.o"
	@echo "... src/GaletDetectorConstruction.i"
	@echo "... src/GaletDetectorConstruction.s"
	@echo "... src/GaletDetectorConstructionMessenger.o"
	@echo "... src/GaletDetectorConstructionMessenger.i"
	@echo "... src/GaletDetectorConstructionMessenger.s"
	@echo "... src/GaletEventAction.o"
	@echo "... src/GaletEventAction.i"
	@echo "... src/GaletEventAction.s"
	@echo "... src/GaletEventActionMessenger.o"
	@echo "... src/GaletEventActionMessenger.i"
	@echo "... src/GaletEventActionMessenger.s"
	@echo "... src/GaletHit.o"
	@echo "... src/GaletHit.i"
	@echo "... src/GaletHit.s"
	@echo "... src/GaletMagneticField.o"
	@echo "... src/GaletMagneticField.i"
	@echo "... src/GaletMagneticField.s"
	@echo "... src/GaletNestedPhantomParameterisation.o"
	@echo "... src/GaletNestedPhantomParameterisation.i"
	@echo "... src/GaletNestedPhantomParameterisation.s"
	@echo "... src/GaletPhantom.o"
	@echo "... src/GaletPhantom.i"
	@echo "... src/GaletPhantom.s"
	@echo "... src/GaletPrimaryGeneratorAction.o"
	@echo "... src/GaletPrimaryGeneratorAction.i"
	@echo "... src/GaletPrimaryGeneratorAction.s"
	@echo "... src/GaletRunAction.o"
	@echo "... src/GaletRunAction.i"
	@echo "... src/GaletRunAction.s"
	@echo "... src/GaletRunActionMessenger.o"
	@echo "... src/GaletRunActionMessenger.i"
	@echo "... src/GaletRunActionMessenger.s"
	@echo "... src/GaletSD.o"
	@echo "... src/GaletSD.i"
	@echo "... src/GaletSD.s"
	@echo "... src/GaletSteppingAction.o"
	@echo "... src/GaletSteppingAction.i"
	@echo "... src/GaletSteppingAction.s"
	@echo "... src/GaletTrackInformation.o"
	@echo "... src/GaletTrackInformation.i"
	@echo "... src/GaletTrackInformation.s"
	@echo "... src/GaletTrackingAction.o"
	@echo "... src/GaletTrackingAction.i"
	@echo "... src/GaletTrackingAction.s"
	@echo "... src/GaletTriggerSD.o"
	@echo "... src/GaletTriggerSD.i"
	@echo "... src/GaletTriggerSD.s"
	@echo "... src/MACParticleConstruction.o"
	@echo "... src/MACParticleConstruction.i"
	@echo "... src/MACParticleConstruction.s"
	@echo "... src/MACPhysicsList.o"
	@echo "... src/MACPhysicsList.i"
	@echo "... src/MACPhysicsList.s"
	@echo "... src/MACPhysicsListMessenger.o"
	@echo "... src/MACPhysicsListMessenger.i"
	@echo "... src/MACPhysicsListMessenger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

